apiVersion: v1
kind: Pod
metadata:
  name: mynginxpod
  labels:
    appname: nginxapp
spec:
  nodeSelector:
    nodepool: app-nodepool
  containers:
  - name: mynginxpod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80